- name: yumリポジトリをインストル
  command: yum localinstall -y https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-ami201503-96-9.6-2.noarch.rpm
  tags: database

- name: PostgreSQLインストル
  yum: name={{item}} state=installed
  with_items:
    - postgresql96
    - postgresql96-server
    - postgresql96-libs
    - postgresql96-contrib
  tags: database
