- name: docker should be installed
  yum: name=docker
  tags: docker

- name: start docker
  service:
    name: docker
    state: started
  tags: docker

- name: epel-release should be installed
  yum: name=epel-release
  tags: docker

- name: python-pip should be install
  yum: name=python-pip
  tags: docker

- name: install docker-compose
  command: pip install docker-compose
  tags: docker

- name: upgrade python
  yum:
    name: python*
    state: latest
  tags: docker

- name: add vagrant user to docker group
  command: usermod -aG docker vagrant
  tags: docker
